# Generated by Django 5.0.6 on 2024-07-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='org_id',
            new_name='orgid',
        ),
    ]
